### ISSUE TITLE
PCB patch Outline Does not work correctly.

### ISSUE THREAD

**Issue by theholyduck** [fellesverkstedet/fabricatable-machines#18]
As per or previous conversations i decided to try the patch suggested in https://github.com/fellesverkstedet/fabricatable-machines/blob/master/humphrey-large-format-cnc/humphrey_v3/img/electronics/possibel_upgrade.JPG

Everything still seems to work but there is no power-out detection at all. Since the drawing there is of a slightly different revision of the pcb than the one we actually have. i have included this drawing of where i cut and where i patched. 
![image](https://user-images.githubusercontent.com/13220084/45261962-ca36db00-b40c-11e8-9bc4-c69c974b7b06.png)

**Comment by theholyduck** [comment]
actually i did just find something that is affected by that patch. with that patch enabled i cant fire up the spindle at all. with it disabled. i can

**Comment by theholyduck** [comment]
i guess this patch isnt strictly speaking necesary. the arduino in the original config does seem to pretty reliably detect a power-cut.

**Comment by Jaknil** [comment]
I have found why it didn't work. It was two things, the signal was not inverting correctly with that setup and I had mixed up the GND (for arduino) with GNDS for the regulator. I have updated the schematic and board accordingly.  (HRBL-nano). 

Since your machine is already correctly throwing an error message when external power is cycled I suggest that you leave it as it is. 

This is the tested and working schematic to constantly send an ABORT on loss of exernal power:
![image](https://user-images.githubusercontent.com/3476653/45450441-8b3caa00-b6d8-11e8-91e7-732eacb3a5b4.png)
